### ISSUE TITLE
Epic

### ISSUE THREAD

**Issue by ThedysonLuzon** [ThedysonLuzon/ASPdotNETDevOps#1]
- [ ] Create a new project with MVC template.
- [ ] Design the database schema for Agile Work Items.
- [ ] Create the model classes for Agile Work Items.
- [ ] Create the controller for Agile Work Items.
- [ ] Create the views for Agile Work Items.
